apiVersion: nais.io/v1alpha1
kind: Alert
metadata:
  name: okosynk-alerts
  labels:
    team: oppgavehandtering
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#oh-prod-varsling'
      prependText: 'Okosynk batch har ikke oppdatert noen oppgaver'
  alerts:
    - alert: okosynk (OS) ingen oppgaver oppdatert
      expr: 'okosynk_job_oppgaver_oppdatert{cronjob="bokosynk001",job="kubernetes-pods"} == 0'
      for: 5m
      action: Se status på batch i kibana
      description: Okosynk (OS) batch job har ikke oppdatert noen oppgaver
      documentation: okosynk
      sla: N/A
      severity: warning
    - alert: okosynk (UR) ingen oppgaver oppdatert
      expr: 'okosynk_job_oppgaver_oppdatert{cronjob="bokosynk002",job="kubernetes-pods"} == 0'
      for: 5m
      action: Se status på batch i kibana
      description: Okosynk (UR) batch job har ikke oppdatert noen oppgaver
      documentation: okosynk
      sla: N/A
      severity: warning