apiVersion: nais.io/v1alpha1
kind: Alert
metadata:
  name: okosynk-alerts
  labels:
    team: oppgavehandtering
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#oh-prod-varsling'
      prependText: 'Okosynk batch ser ut til å ha feilet'
    email:
      to: 'jorgen.markussen@nav.no'
  alerts:
    - alert: Okosynk batch status failed
      expr: 'sum(rate(kube_job_status_failed{namespace="okosynk"}[24h])) > 0'
      for: 5m
      action: Se status på batch i kibana
      description: Okosynk (OS) batch job ser ut til å ha feilet under kjøring
      documentation: okosynk
      sla: N/A
      severity: critical