apiVersion: nais.io/v1alpha1
kind: Alert
metadata:
  name: okosynk-alerts
  labels:
    team: oppgavehandtering
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#oh-prod-varsling'
      prependText: 'Okosynk batch har ikke opprettet noen nye oppgaver | '
  alerts:
    - alert: okosynk (OS) ingen nye oppgaver
      expr: 'okosynk_job_oppgaver_opprettet{cronjob="bokosynk001",job="kubernetes-pods"} == 0'
      for: 5m
      action: Se logger
      description: Okosynk (OS) batch job har ikke opprettet noen nye oppgaver
      documentation: okosynk
      sla: N/A
      severity: warning
    - alert: okosynk (UR) ingen nye oppgaver
      expr: 'okosynk_job_oppgaver_opprettet{cronjob="bokosynk002",job="kubernetes-pods"} == 0'
      for: 5m
      action: Se logger
      description: Okosynk (UR) batch job har ikke opprettet noen nye oppgaver
      documentation: okosynk
      sla: N/A
      severity: warning