apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: okosynk-os
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: okosynk-alerts
      rules:
        - alert:
  receivers: # receivers for all alerts below
    slack:
      channel: '#team-mob-alerts-dev'
      prependText: 'Varsel fra Okosynk: '
      httpConfig:
        proxyURL: http://webproxy.nais:8088
      email_configs:
        - to: lars.hartvigsen@nav.no
  alerts:
    - alert: okosynk_general_check_logs_preprod_os
      expr: 'okosynk_job_oppgaver_opprettet{cronjob="bokosynk002"} > 5000'
      for: 5m
      annotations:
        consequence: Mange oppgaver som må håndteres manuelt
        action: Sjekk om noe spesielt har skjedd som har ført til mange nye oppgaver
        summary: Vet ikke hva mer jeg kan si
      labels:
        namespace: okonomi
        severity: danger
    - alert: okosynk_general_check_logs_preprod_ur
      expr: 'okosynk_job_oppgaver_opprettet{cronjob="bokosynk001"} > 5000'
      for: 5m
      annotations:
        consequence: Mange oppgaver som må håndteres manuelt
        action: Sjekk om noe spesielt har skjedd som har ført til mange nye oppgaver
        summary: Vet ikke hva mer jeg kan si
      labels:
        namespace: okonomi
        severity: danger
