apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: okosynk
  namespace: okosynk
spec:
  schedule: "0 5 * * *" # Every morning at 04:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: okosynk
              secret:
                secretName: okosynk
          restartPolicy: Never
          containers:
            - name: okosynk
              image: repo.adeo.no:5443/okosynk:20200128.1305.ec0a2791
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
              env:
                - name: OKOSYNK_SHOULD_RUN_DRY
                  value: "false"
                - name: NAV_TRUSTSTORE_KEYSTOREALIAS
                  value: na
                - name: NAV_TRUSTSTORE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: nav_truststore_password
                - name: NAV_TRUSTSTORE_PATH
                  value: "/var/run/secrets/naisd.io/nav_truststore_path"
                - name: SRVOKOSYNK_KEYSTOREALIAS
                  value: app-key
                - name: SRVOKOSYNK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: srvokosynk_password
                - name: SRVOKOSYNK_KEYSTORE
                  value: /var/run/secrets/naisd.io/srvokosynk_keystore
                - name: VIRKSOMHET_OPPGAVEBEHANDLING_V3_ENDPOINTURL
                  # value: https://wasapp-q3.adeo.no/nav-gsak-ws/OppgavebehandlingV3 #talking directly to oppgave endpoint
                  value: https://service-gw.adeo.no # Talking with oppgave via service gateway
                - name: VIRKSOMHET_OPPGAVE_V3_ENDPOINTURL
                  # value: https://wasapp-q3.adeo.no/nav-gsak-ws/OppgaveV3 #talking directly to oppgave endpoint
                  value: https://service-gw.adeo.no # Talking with oppgave via service gateway
                - name: SERVICEGATEWAY_URL
                  value: https://service-gw.adeo.no
                - name: OPPGAVE_URL
                  value: https://oppgave.nais.adeo.no/api/v1/oppgaver
                - name: AKTOERREGISTER_URL
                  value: https://app.adeo.no/aktoerregister/api/v1/identer
                - name: REST_STS_URL
                  value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
                - name: PUSH_GATEWAY_ADDRESS
                  value: nais-prometheus-prometheus-pushgateway.nais:9091
                - name: SRVBOKOSYNK_USERNAME
                  value: srvbokosynk
                - name: SRVBOKOSYNK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: srvbokosynk_password
                - name: SRVBOKOSYNK001_USERNAME
                  value: srvbokosynk001
                - name: SRVBOKOSYNK001_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: srvbokosynk001_password
                - name: SRVBOKOSYNK002_USERNAME
                  value: srvbokosynk002
                - name: SRVBOKOSYNK002_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: srvbokosynk002_password
                - name: OSFTPBASEURL_URL
                  value: sftp://filmottak.adeo.no:22/home/srvokosynksftp/inbound/os.input
                - name: OSFTPCREDENTIALS_USERNAME
                  value: srvokosynksftp
                - name: OSFTPCREDENTIALS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: osftpcredentials_password
                - name: URFTPBASEURL_URL
                  value: sftp://filmottak.adeo.no:22/home/srvokosynksftp/inbound/ur.input
                - name: URFTPCREDENTIALS_USERNAME
                  value: srvokosynksftp
                - name: URFTPCREDENTIALS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: okosynk
                      key: urftpcredentials_password
                - name: SECURITYTOKENSERVICE_URL
                  value: https://sts.adeo.no/SecurityTokenServiceProvider/

                - name: FILE_READER_RETRY_WAIT_TIME_IN_MS
                  value: "10000"
                - name: FILE_READER_MAX_NUMBER_OF_TRIES
                  value: "2"
                - name: BATCH_RETRY_WAIT_TIME_IN_MS
                  value: "300000"
                - name: BATCH_MAX_NUMBER_OF_TRIES
                  value: "18"

              volumeMounts:
                - name: okosynk
                  mountPath: "/var/run/secrets/naisd.io/"