apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: okosynkur
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: okosynk-ur-alerts
      rules:
        - alert: okosynk-UR sender varsel
          expr: okosynk_ur_batch_alert > 0
          for: 1m
          annotations:
            action: "Sjekk hvorfor okosynk-ur gir varsel"
            summary: "okosynk-ur gir varsel. Sjekk hvorfor"
          labels:
            namespace: okonomi
            severity: danger
            okosynk_ur_type: okosynkur
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: okosynk-ur-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: okosynk-ur-slack
spec:
  receivers:
    - name: okosynk-ur-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-dev'
          httpConfig:
            proxyURL: http://webproxy.nais:8088
          iconEmoji: ':alert:'
          username: 'Alert dev-fss'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "okosynk_ur_type"
        matchType: "="
        value: "okosynkur"
    groupInterval: 10s
    groupWait: 5s
    receiver: okosynk-ur-receiver
    repeatInterval: 1440m

