apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: oppgavehandtering
  name: okosynk
  namespace: oppgavehandtering
spec:
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  image: {{image}}
  schedule: "0 4 * * *" # Every morning at 04:00 UTC
  webproxy: true
  ttlSecondsAfterFinished: 172800
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 250m
      memory: 1Gi
  env:
    - name: OKOSYNK_SHOULD_RUN_DRY
      value: "false"
    - name: OPPGAVE_URL
      value: https://oppgave.nais.preprod.local/api/v1/oppgaver
    - name: AKTOERREGISTER_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1/identer
    - name: REST_STS_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q3.preprod.local/SecurityTokenServiceProvider/
    - name: PUSH_GATEWAY_ADDRESS
      value: nais-prometheus-pushgateway.nais:9091
    - name: FILE_READER_RETRY_WAIT_TIME_IN_MS
      value: "0"
    - name: FILE_READER_MAX_NUMBER_OF_TRIES
      value: "1"
    - name: BATCH_RETRY_WAIT_TIME_IN_MS
      value: "30000"
    - name: BATCH_MAX_NUMBER_OF_TRIES
      value: "3"
    - name: SRVBOKOSYNK001_USERNAME
      value: srvbokosynk001
    - name: SRVBOKOSYNK002_USERNAME
      value: srvbokosynk002
    - name: OSFTPBASEURL_URL
      value: sftp://filmottak.preprod.local:22/home/srvokosynksftp/inbound/os.input
    - name: OSFTPCREDENTIALS_USERNAME
      value: srvokosynksftp
    - name: URFTPBASEURL_URL
      value: sftp://filmottak.preprod.local:22/home/srvokosynksftp/inbound/ur.input
    - name: URFTPCREDENTIALS_USERNAME
      value: srvokosynksftp
  vault:
    enabled: true
    paths:
      - format: env
        kvPath: serviceuser/data/dev/srvbokosynk001/password
        mountPath: /var/run/secrets/nais.io/vault
    sidecar: true