apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: okonomi
  name: okosynkos
  namespace: okonomi
spec:
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  image: {{image}}
  schedule: "0 4 * * *" # Every morning at 04:00 UTC
  webproxy: true
  backoffLimit: 3
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 250m
      memory: 1Gi
  secureLogs:
    enabled: true
  env:
    - name: OPPGAVE_URL
      value: https://oppgave.nais.preprod.local/api/v1/oppgaver
    - name: REST_STS_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q3.preprod.local/SecurityTokenServiceProvider/
    - name: PUSH_GATEWAY_ADDRESS
      value: prometheus-pushgateway.nais-system:9091
    - name: FILE_READER_RETRY_WAIT_TIME_IN_MS
      value: "0"
    - name: FILE_READER_MAX_NUMBER_OF_TRIES
      value: "1"
    - name: BATCH_RETRY_WAIT_TIME_IN_MS
      value: "30000"
    - name: BATCH_MAX_NUMBER_OF_TRIES
      value: "3"
    - name: OSFTPBASEURL_URL
      value: sftp://filmottak.preprod.local:22/home/srvokosynksftp/inbound/OS.INPUT
    - name: URFTPBASEURL_URL
      value: sftp://filmottak.preprod.local:22/home/srvokosynksftp/inbound/UR.INPUT
    - name: AZURE_APP_SCOPE_OPPGAVE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: SHOULD_RUN_OS_OR_UR
      value: OS
    - name: PDL_URL
      value: https://pdl-api-q1.dev.intern.nav.no/graphql

  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvbokosynk001
        mountPath: /secrets/serviceuser/okosynk/srvbokosynk001
      - kvPath: serviceuser/data/dev/srvbokosynk002
        mountPath: /secrets/serviceuser/okosynk/srvbokosynk002
      - kvPath: serviceuser/data/dev/srvokosynksftp
        mountPath: /secrets/serviceuser/okosynk/srvokosynksftp
    sidecar: true
status: {}
