apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: oppgavehandtering
  name: okosynkos
  namespace: oppgavehandtering
spec:
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  image: {{image}}
  schedule: "0 4 * * *" # Every morning at 04:00 UTC
  webproxy: true
  ttlSecondsAfterFinished: 172800
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 4Gi
  env:
    - name: OPPGAVE_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: AKTOERREGISTER_URL
      value: https://app.adeo.no/aktoerregister/api/v1/identer
    - name: REST_STS_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: PUSH_GATEWAY_ADDRESS
      value: nais-prometheus-pushgateway.nais:9091
    - name: FILE_READER_RETRY_WAIT_TIME_IN_MS
      value: "0"
    - name: FILE_READER_MAX_NUMBER_OF_TRIES
      value: "1"
    - name: BATCH_RETRY_WAIT_TIME_IN_MS
      value: "300000"
    - name: BATCH_MAX_NUMBER_OF_TRIES
      value: "18"
    - name: OSFTPBASEURL_URL
      value: sftp://filmottak.adeo.no:22/home/srvokosynksftp/inbound/os.input
    - name: URFTPBASEURL_URL
      value: sftp://filmottak.adeo.no:22/home/srvokosynksftp/inbound/ur.input
    - name: AZURE_APP_SCOPE_OPPGAVE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: SHOULD_RUN_OS_OR_UR
      value: OS
    - name: SHOULD_AUTHENTICATE_USING_AZURE_AD_AGAINST_OPPGAVE
      value: "true"
    - name: SHOULD_CONVERT_FOLKEREGISTERIDENT_TO_AKTOERID
      value: "true"
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SHOULD_PREFER_PDL_TO_AKTOERREGISTERET
      value: "false"

  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvbokosynk001
        mountPath: /secrets/serviceuser/okosynk/srvbokosynk001
      - kvPath: serviceuser/data/prod/srvbokosynk002
        mountPath: /secrets/serviceuser/okosynk/srvbokosynk002
      - kvPath: serviceuser/data/prod/srvokosynksftp
        mountPath: /secrets/serviceuser/okosynk/srvokosynksftp
    sidecar: true
status: {}