name: Deploy alarmer
on:
  push:
    branches:
      - main

jobs:
  deploy-alerts-dev:
    name: Deploy alarmer til dev
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut kode
        uses: actions/checkout@v3
      - name: Deploy ur til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/alerts-job-dev-ur.yaml
      - name: Deploy os til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/alerts-job-dev-os.yaml
