name: Deploy alerts

on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts-job-dev-os.yaml'
      - '.nais/alerts-job-prod-os.yaml'
      - '.nais/alerts-job-dev-ur.yaml'
      - '.nais/alerts-job-prod-ur.yaml'

permissions:
  contents: "write"
  id-token: "write"

jobs:
  deploy-os-dev:
    name: Deploy os to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/alerts-job-dev-os.yaml

  deploy-ur-dev:
    name: Deploy ur to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/alerts-job-dev-ur.yaml

  deploy-os-prod:
    name: Deploy os to prod-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/alerts-job-prod-os.yaml

  deploy-ur-prod:
    name: Deploy ur to prod-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/alerts-job-prod-ur.yaml
